#
#   Profesor, intenté de todo pero tanto en el CI y el CD
#   me aparece este mismo error y realmente no sé a qué se deba
#   también puede ver el error más detalladamente en el github actions
#
#   /home/runner/work/express_testing/express_testing/node_modules/pg/lib/sasl.js:24
#    throw new Error('SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string')
#

name: Express.js CI
on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: prueba1
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "18.12.1"

      - name: Installing Dependecies
        run: npm i

      - name: testing our app
        run: npm test
